#!/usr/bin/env bash
# Tests the global git hooks (git-hooks/) and the Claude Code hooks (hooks/claude/).
# Uses throwaway repositories and an isolated git config; never touches the real HOME.
# Usage: tests/hooks.test.sh
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/agent-harness-hooks.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT
PASSED=0
FAILED=0

pass() { printf '  ✔ %s\n' "$1"; PASSED=$((PASSED + 1)); }
fail() { printf '  ✘ %s\n' "$1"; FAILED=$((FAILED + 1)); }
check() { if eval "$2"; then pass "$1"; else fail "$1"; fi; }

# Isolated git environment using the global hooks under test
export HOME="$WORK/home" XDG_CONFIG_HOME="$WORK/home/.config" GIT_CONFIG_NOSYSTEM=1
mkdir -p "$HOME"
git config --global user.name "Test User"
git config --global user.email "test@example.com"
git config --global init.defaultBranch main
git config --global core.hooksPath "$REPO/git-hooks"
git config --global commit.gpgsign false
# Test repos behave as harness-enabled projects unless a test disables them
git config --global harness.enabled true
CLI="$REPO/bin/tack"

new_repo() {
  rm -rf "$1"
  git init -q "$1"
  git -C "$1" commit -q --allow-empty -m "chore: initial commit"
}

commit() { git -C "$R" commit -q --allow-empty -m "$1" >/dev/null 2>&1; }
# A commit that prepares a scenario must succeed, or the assertions after it would silently
# check the previous commit instead
setup_commit() {
  local subject="${1%%$'\n'*}"
  if commit "$1" && [ "$(git -C "$R" log -1 --format=%s)" = "$subject" ]; then
    return 0
  fi
  fail "setup commit failed: $subject"
}
last_message() { git -C "$R" log -1 --format=%B; }

echo "commit-msg: Conventional Commits"
R="$WORK/repo"
new_repo "$R"
check "accepts 'feat(auth): add login'" "commit 'feat(auth): add login'"
check "rejection points to the config command" "{ git -C '$R' commit -q --allow-empty -m 'bad subject' 2>&1 || true; } | grep -q 'tack config conventional-commits false'"
check "accepts breaking change 'feat!: drop v1 API'" "commit 'feat!: drop v1 API'"
check "accepts 'fix: handle empty cart'" "commit 'fix: handle empty cart'"
check "rejects 'added login'" "! commit 'added login'"
check "rejects unknown type 'feature: x'" "! commit 'feature: add x'"
check "rejects missing description 'fix:'" "! commit 'fix:'"
check "rejects subject over 100 chars" "! commit \"fix: $(printf 'x%.0s' $(seq 1 100))\""
check "accepts autosquash 'fixup! feat: x'" "commit 'fixup! feat(auth): add login'"
check "accepts merge messages" "commit \"Merge branch 'feature'\""
check "accepts revert messages" "commit 'Revert \"feat: x\"'"

echo "commit-msg: AI attribution is removed"
setup_commit "$(printf 'feat: add export\n\nExports orders as CSV.\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n')"
check "Co-Authored-By Claude removed" "! last_message | grep -qi 'co-authored-by'"
check "body is kept" "last_message | grep -q 'Exports orders as CSV.'"
setup_commit "$(printf 'fix: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n')"
check "'Generated with Claude Code' line removed" "! last_message | grep -qi 'generated with'"
setup_commit "$(printf 'fix: y\n\nCo-authored-by: Codex <codex@openai.com>\nCo-authored-by: Ana Dev <ana@example.com>\n')"
check "Codex trailer removed" "! last_message | grep -qi codex"
check "human co-author kept" "last_message | grep -q 'Ana Dev'"
check "subject mentioning a tool is kept" "commit 'fix(codegen): skip files generated by Copilot' && [ \"\$(git -C '$R' log -1 --format=%s)\" = 'fix(codegen): skip files generated by Copilot' ]"
setup_commit "$(printf 'fix: parser\n\nHandles files generated by Cursor IDE exports.\nThe lexer is generated by ANTLR.\n')"
check "body lines mentioning generated files are kept" "last_message | grep -q 'Cursor IDE exports' && last_message | grep -q 'generated by ANTLR'"
setup_commit "$(printf 'fix: z\n\nCo-authored-by: Devin Smith <devin@example.com>\nCo-authored-by: Gemma Cursor <gemma@cursor-labs.example>\n')"
check "human co-authors with tool-like names are kept" "last_message | grep -q 'Devin Smith' && last_message | grep -q 'Gemma Cursor'"
setup_commit "$(printf 'fix: w\n\nCo-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n')"
check "Copilot and model-named Claude trailers removed" "! last_message | grep -qiE 'copilot|claude'"

echo "commit-msg: per-repo opt-out"
git -C "$R" config harness.conventionalCommits false
check "free-form message allowed after opt-out" "commit 'Update stuff'"
setup_commit "$(printf 'Update more\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n')"
check "AI attribution still removed after opt-out" "! last_message | grep -qi claude"
git -C "$R" config --unset harness.conventionalCommits

echo "pre-commit: secrets never get committed"
S="$WORK/secrets"
new_repo "$S"
stage() { mkdir -p "$(dirname "$S/$1")" && printf '%s\n' "$2" > "$S/$1" && git -C "$S" add -f "$1"; }
# --allow-empty: if staging failed, the commit succeeds and a "refused" check fails loudly
try_commit() { git -C "$S" commit -q --allow-empty -m "chore: test" >/dev/null 2>&1; }
reset_index() { git -C "$S" reset -q; git -C "$S" clean -qfdx; }
stage .env "API_KEY=abc"
check "a .env file is refused" "! try_commit"
reset_index
stage config/.env.production "DB=x"
check "a nested .env.production is refused" "! try_commit"
reset_index
stage .env.example "API_KEY="
check ".env.example is allowed" "try_commit"
stage id_rsa "-----BEGIN OPENSSH PRIVATE KEY-----"
check "a private key is refused" "! try_commit"
reset_index
stage settings.py "AWS_ACCESS_KEY_ID = 'AKIAIOSFODNN7EXAMPLE'"
check "an AWS access key is refused" "! try_commit"
reset_index
stage deploy.sh "export GITHUB_TOKEN=ghp_0123456789abcdefghijklmnopqrstuvwxyzAB"
check "a GitHub token is refused" "! try_commit"
reset_index
stage pay.ts "const key = 'sk_live_0123456789abcdefghijklmn'"
check "a Stripe live key is refused" "! try_commit"
reset_index
stage notes.md "Set AWS_ACCESS_KEY_ID in your environment; never commit .env files."
check "text that only mentions secrets is allowed" "try_commit"
stage .env "API_KEY=abc"
check "override allows a deliberate commit" "HARNESS_ALLOW_SECRETS=1 try_commit"
git -C "$S" config harness.enabled false
stage .env.local "X=1"
check "also active in projects that aren't enabled" "! try_commit"
reset_index

echo "Local repository hooks keep working (chaining)"
cat > "$R/.git/hooks/pre-commit" <<EOF
#!/usr/bin/env bash
echo ran > "$WORK/pre-commit-ran"
EOF
cat > "$R/.git/hooks/commit-msg" <<EOF
#!/usr/bin/env bash
echo "\$1" > "$WORK/commit-msg-ran"
EOF
chmod +x "$R/.git/hooks/pre-commit" "$R/.git/hooks/commit-msg"
setup_commit "docs: chained hooks"
check "local pre-commit ran" "[ -f '$WORK/pre-commit-ran' ]"
check "local commit-msg ran with the message file" "[ -s '$WORK/commit-msg-ran' ]"
cat > "$R/.git/hooks/pre-commit" <<'EOF'
#!/usr/bin/env bash
echo "lint failed" >&2
exit 1
EOF
check "a failing local pre-commit still blocks the commit" "! commit 'docs: blocked'"
rm -f "$R/.git/hooks/pre-commit" "$R/.git/hooks/commit-msg"

echo "pre-push: main is protected"
REMOTE="$WORK/remote.git"
git init -q --bare "$REMOTE"
R="$WORK/pusher"
new_repo "$R"
git -C "$R" remote add origin "$REMOTE"
push() { git -C "$R" push -q "$@" >/dev/null 2>&1; }
check "normal push to main works" "push origin main"
setup_commit "feat: second"
check "fast-forward push to main works" "push origin main"
before="$(git -C "$R" rev-parse HEAD)"
git -C "$R" commit -q --amend --allow-empty -m "feat: second (amended)" >/dev/null 2>&1
check "history was rewritten locally (test precondition)" "[ \"\$(git -C '$R' rev-parse HEAD)\" != '$before' ]"
check "force push to main is refused" "! push --force origin main"
check "force-with-lease to main is refused" "! push --force-with-lease origin main"
check "override variable allows it" "HARNESS_ALLOW_FORCE_PUSH=1 push --force origin main"
check "deleting main on the remote is refused" "! push origin :main"
git -C "$R" switch -q -c feat/x
setup_commit "feat: on branch"
check "push of a feature branch works" "push origin feat/x"
before="$(git -C "$R" rev-parse HEAD)"
git -C "$R" commit -q --amend --allow-empty -m "feat: on branch (amended)" >/dev/null 2>&1
check "feature branch rewritten locally (test precondition)" "[ \"\$(git -C '$R' rev-parse HEAD)\" != '$before' ]"
check "force push to a feature branch is allowed" "push --force origin feat/x"

echo "pre-push: tags follow the release convention in enabled projects"
git -C "$R" switch -q main
git -C "$R" tag v1.0.0
check "lightweight tag is refused" "! push origin v1.0.0"
git -C "$R" tag -d v1.0.0 >/dev/null
git -C "$R" tag -a v1.0.0 -m v1.0.0
check "annotated vX.Y.Z tag is accepted" "push origin v1.0.0"
git -C "$R" tag -a v2.0.0-rc.1 -m v2.0.0-rc.1
check "annotated pre-release tag is accepted" "push origin v2.0.0-rc.1"
git -C "$R" tag -a release-1 -m release-1
check "tag name outside the convention is refused" "! push origin release-1"
check "deleting a published tag is refused" "! push origin :refs/tags/v1.0.0"
git -C "$R" tag -d v1.0.0 >/dev/null
git -C "$R" tag -a v1.0.0 -m "moved" HEAD~1
check "moving a published tag is refused" "! push --force origin v1.0.0"
check "override allows a deliberate tag change" "HARNESS_ALLOW_TAG=1 push --force origin v1.0.0"
git -C "$R" config harness.enabled false
check "projects not enabled can push any tag" "push origin release-1"
git -C "$R" config --unset harness.enabled
git -C "$R" switch -q feat/x

echo "pre-push: local pre-push hook receives stdin"
cat > "$R/.git/hooks/pre-push" <<EOF
#!/usr/bin/env bash
cat > "$WORK/pre-push-stdin"
EOF
chmod +x "$R/.git/hooks/pre-push"
setup_commit "feat: more"
push origin feat/x
check "local pre-push ran with the ref list" "grep -q 'refs/heads/feat/x' '$WORK/pre-push-stdin'"
check "ref list keeps its trailing newline" "[ \"\$(tail -c 1 '$WORK/pre-push-stdin' | od -An -c | tr -d ' ')\" = '\\n' ]"
# The usual hook shape (as in git's pre-push.sample) must see every ref
cat > "$R/.git/hooks/pre-push" <<EOF
#!/usr/bin/env bash
n=0
while read -r _local_ref _local_sha _remote_ref _remote_sha; do n=\$((n + 1)); done
echo "\$n" > "$WORK/pre-push-count"
EOF
setup_commit "feat: even more"
push origin feat/x
check "local pre-push 'while read' loop sees the pushed ref" "[ \"\$(cat '$WORK/pre-push-count')\" = 1 ]"
printf '#!/usr/bin/env bash\nexit 1\n' > "$R/.git/hooks/pre-push"
setup_commit "feat: blocked push"
check "a failing local pre-push still blocks the push" "! push origin feat/x"
rm -f "$R/.git/hooks/pre-push"

echo "Server-side hooks of local bare repositories keep working"
BARE="$WORK/deploy.git"
git init -q --bare "$BARE"
for hook in pre-receive post-receive; do
  printf '#!/usr/bin/env bash\ncat > "%s/%s-ran"\n' "$WORK" "$hook" > "$BARE/hooks/$hook"
  chmod +x "$BARE/hooks/$hook"
done
R="$WORK/deployer"
new_repo "$R"
git -C "$R" remote add deploy "$BARE"
check "push to the bare repo works" "push deploy main"
check "its pre-receive ran with the ref list" "grep -q refs/heads/main '$WORK/pre-receive-ran'"
check "its post-receive ran" "grep -q refs/heads/main '$WORK/post-receive-ran'"
printf '#!/usr/bin/env bash\necho rejected >&2\nexit 1\n' > "$BARE/hooks/pre-receive"
setup_commit "feat: rejected by the server"
check "a failing pre-receive still rejects the push" "! push deploy main"

echo "Claude hook: guard-bash"
GUARD="$REPO/hooks/claude/guard-bash.sh"
R="$WORK/guard"
new_repo "$R"
guard() {
  local cmd="$1" json
  if command -v jq >/dev/null 2>&1; then
    json="$(jq -n --arg c "$cmd" --arg d "$R" '{tool_name:"Bash",tool_input:{command:$c},cwd:$d}')"
  else
    json="$(python3 -c 'import json,sys; print(json.dumps({"tool_name":"Bash","tool_input":{"command":sys.argv[1]},"cwd":sys.argv[2]}))' "$cmd" "$R")"
  fi
  printf '%s' "$json" | bash "$GUARD"
}
# A crash (non-zero exit) or malformed JSON must never pass as "allow"
decision() {
  local out rc
  out="$(guard "$1")"
  rc=$?
  if [ "$rc" -ne 0 ]; then echo "error: exit $rc"; return; fi
  if [ -n "$out" ] && ! printf '%s' "$out" | python3 -c 'import json, sys; json.load(sys.stdin)' 2>/dev/null; then
    echo "error: invalid JSON: $out"
    return
  fi
  case "$out" in
    *'"deny"'*) echo deny ;;
    *'"ask"'*) echo ask ;;
    '') echo allow ;;
    *) echo "unexpected: $out" ;;
  esac
}
expect() { check "$2 → $1" "[ \"\$(decision $(printf '%q' "$2"))\" = '$1' ]"; }

expect allow "ls -la"
expect allow "git status && git diff"
expect allow "git push origin feat/login"
expect allow "git commit -m 'fix: x'"
expect allow "rm -rf node_modules dist"
expect allow "rm -rf /tmp/build-cache"
expect allow "truncate -s 0 app.log"
expect allow "git restore --staged src/app.ts"
expect allow "git clean -n"
expect deny "git push --force origin main"
expect deny "git push -f origin master"
expect deny "git push origin +main"
expect deny "git push origin --delete main"
expect deny "git -C /some/path push --force-with-lease origin main"
expect deny "git commit --no-verify -m 'feat: x'"
expect deny "git push --no-verify origin feat/x"
expect deny "rm -rf /"
expect deny "rm -rf ~"
expect deny "rm -rf \$HOME"
expect deny "rm -rf .."
expect deny "cd src && rm -rf ../*"
expect deny "rm -fr ~/"
expect ask "git push --force origin feat/x"
expect ask "git reset --hard HEAD~2"
expect ask "git clean -fd"
expect ask "git checkout -- ."
expect ask "git branch -D old-feature"
expect ask "git stash clear"
expect ask "rm -rf ./*"
expect ask "rm -rf /etc/nginx"
expect ask "rm -rf ~/projects/old"
expect ask "psql -c 'DROP DATABASE app'"
expect ask "mysql -e 'TRUNCATE TABLE users'"
expect ask "php artisan migrate:fresh --seed"
expect ask "npx prisma migrate reset"
expect deny "git push --force"
expect deny "git push --force-with-lease"
git -C "$R" switch -q -c feat/y
expect ask "git push --force-with-lease"
expect ask "git push --force"

# Quoting: quoted text is data, quoted targets are still targets
expect allow "git commit -m 'docs: explain why --no-verify is denied'"
expect allow "git commit -m \"fix: handle a; rm -rf / edge\""
expect allow "grep -rn \"DROP TABLE\" migrations/"
expect allow "echo 'git push --force origin main'"
expect deny "rm -rf \"\$HOME\""
expect deny "rm -rf \"/\""
expect deny "rm -rf '~'"
expect deny "rm -rf --no-preserve-root /tmp/x"
# Short options and hook bypasses
expect deny "git commit -n -m 'fix: x'"
expect deny "git commit -nm 'fix: x'"
expect deny "git commit -anm 'fix: x'"
expect allow "git commit -m 'fix: n is fine in a message'"
expect allow "git commit -mnote"
expect allow "git push -n origin feat/x"
expect deny "git -c core.hooksPath=/dev/null commit -m 'fix: x'"
expect deny "git config core.hooksPath /dev/null"
expect allow "git config --get core.hooksPath"
# Wrappers, absolute paths and nested commands
expect deny "env FOO=1 git push --force origin main"
expect deny "/usr/bin/git push --force origin main"
expect deny "sudo rm -rf /"
expect deny "sleep 1 & rm -rf ~"
expect deny "bash -c \"rm -rf ~\""
expect deny "sh -c 'git push -f origin main'"
expect deny "eval rm -rf ~"
expect deny "echo \$(rm -rf ~)"
expect deny "timeout 5 git push --force origin main"
# Push targets
expect deny "git push origin :main"
expect deny "git push --force origin refs/heads/main"
expect deny "git push --force origin feat/y:main"
expect deny "git push --mirror"
# Heredoc bodies are data
expect allow "$(printf 'cat > notes.md <<EOF\nNever run rm -rf / or git push --force origin main\nEOF')"
expect allow "$(printf 'git commit -F - <<'"'"'MSG'"'"'\nfix: x\n\nmentions --no-verify\nMSG')"
expect deny "$(printf 'cat > a.txt <<EOF\ntext\nEOF\nrm -rf ~')"
# Discarding changes
expect ask "git restore src/app.ts"
expect allow "git restore --staged src/app.ts"
expect ask "git checkout -- src/app.ts"
expect ask "git checkout -f main"
expect allow "git checkout -b feat/new"
expect ask "git switch --discard-changes main"
expect allow "git switch main"
expect ask "git branch -Df old"
expect allow "git branch -d merged"
# A deny later in the command wins over an earlier ask
expect deny "git reset --hard && rm -rf /"
# Redirection targets are not rm targets
expect allow "rm -rf dist 2> /dev/null"
expect ask "rm -rf /etc/foo\\ bar"
check "invalid JSON input is allowed (fails open)" "[ -z \"\$(printf 'not json' | bash '$GUARD')\" ]"

echo "Claude hooks without jq (python3 fallback)"
NOJQ="$WORK/bin-no-jq"
mkdir -p "$NOJQ"
for tool in bash env git python3 awk sed grep cat tr od head tail mktemp rm dirname basename; do
  [ -x "$(command -v "$tool")" ] && ln -sf "$(command -v "$tool")" "$NOJQ/$tool"
done
nojq_decision() {
  local json out
  json="$(python3 -c 'import json,sys; print(json.dumps({"tool_input":{"command":sys.argv[1]},"cwd":sys.argv[2]}))' "$1" "$R")"
  out="$(printf '%s' "$json" | PATH="$NOJQ" bash "$GUARD")" || { echo "error: exit $?"; return; }
  [ -z "$out" ] && { echo allow; return; }
  printf '%s' "$out" | python3 -c 'import json,sys; print(json.load(sys.stdin)["hookSpecificOutput"]["permissionDecision"])' 2>/dev/null \
    || echo "error: invalid JSON: $out"
}
check "no jq: deny still works" "[ \"\$(nojq_decision 'rm -rf ~')\" = deny ]"
check "no jq: ask still works" "[ \"\$(nojq_decision 'git reset --hard')\" = ask ]"
check "no jq: allow still works" "[ \"\$(nojq_decision 'ls -la')\" = allow ]"
check "no jq: reasons with quotes and backslashes stay valid JSON" "[ \"\$(nojq_decision 'rm -rf /etc/a\\\\ \"b\"')\" = ask ]"
check "no jq: session-context still answers" "printf '{\"cwd\":\"%s\"}' '$R' | PATH='$NOJQ' bash '$REPO/hooks/claude/session-context.sh' | python3 -c 'import json,sys; json.load(sys.stdin)'"

echo "Switch: harness enable/disable/status"
R="$WORK/switch"
new_repo "$R"
git config --global --unset harness.enabled
status_of() { (cd "${1:-$R}" && "$CLI" status) | sed -n '1p'; }
check "disabled by default" "[ \"\$(status_of)\" = disabled ]"
check "status exits 1 when disabled" "! (cd '$R' && '$CLI' status --quiet)"
check "free-form commits allowed when disabled" "commit 'quick fix'"
setup_commit "$(printf 'wip\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n')"
check "AI attribution still removed when disabled" "! last_message | grep -qi claude"
(cd "$R" && "$CLI" enable >/dev/null)
check "enable (local) turns it on" "[ \"\$(status_of)\" = enabled ]"
check "local enable leaves the repo untouched" "[ ! -e '$R/.tack' ] && [ ! -e '$R/.harness' ]"
check "Conventional Commits enforced once enabled" "! commit 'quick fix'"
(cd "$R" && "$CLI" disable >/dev/null)
check "disable turns it off" "[ \"\$(status_of)\" = disabled ]"
(cd "$R" && "$CLI" enable --shared >/dev/null)
check "enable --shared creates .tack" "[ -f '$R/.tack' ]"
git -C "$R" config --unset tack.enabled
check "the .tack file alone enables it" "[ \"\$(status_of)\" = enabled ]"
mv "$R/.tack" "$R/.harness"
check "a legacy .harness file still enables it" "[ \"\$(status_of)\" = enabled ]"
(cd "$R" && "$CLI" disable >/dev/null)
check "disable removes the file" "[ ! -e '$R/.harness' ] && [ \"\$(status_of)\" = disabled ]"
git config --global harness.enabled true
check "global true enables every repo" "[ \"\$(status_of '$WORK/repo')\" = enabled ]"
check "a local false wins over global true" "[ \"\$(status_of)\" = disabled ]"
check "outside a git repo: disabled" "[ \"\$(status_of '$WORK')\" = disabled ]"
check "unknown command exits 2" "(cd '$R' && '$CLI' nope >/dev/null 2>&1); [ \$? -eq 2 ]"

echo "Claude hook: session-context"
SESSION="$REPO/hooks/claude/session-context.sh"
session() { printf '{"cwd":"%s"}' "$1" | bash "$SESSION"; }
check "enabled project: says ENABLED" "session '$WORK/repo' | grep -q 'ENABLED for this project'"
check "disabled project: says NOT enabled" "session '$R' | grep -q 'NOT enabled'"
check "output is valid JSON for SessionStart" "session '$R' | python3 -c 'import json,sys; d=json.load(sys.stdin); assert d[\"hookSpecificOutput\"][\"hookEventName\"]==\"SessionStart\"'"
check "auto mode: asks the assistant to pick a level per task" "session '$WORK/repo' | grep -q 'mode: auto.*pick the workflow level'"
check "every mode: asks the assistant to ask when in doubt" "session '$WORK/repo' | grep -q 'Ask the user whenever you have a real doubt'"
check "every mode: states the core rules without loading the skill" "session '$WORK/repo' | grep -q 'At every level: work on a branch off main, test the change, and make a Conventional Commit for each verified milestone'"
git -C "$WORK/repo" config harness.mode lite
check "fixed mode: names the level to apply" "session '$WORK/repo' | grep -q 'mode: lite.*Apply the lite mode rules below'"
check "fixed mode: injects that mode's rules" "session '$WORK/repo' | grep -q 'Plan: none.'"
git -C "$WORK/repo" config --unset harness.mode
check "auto mode: lists the modes to choose from" "session '$WORK/repo' | grep -q 'strict: several modules'"
check "token toggles: defaults add nothing" "! session '$WORK/repo' | grep -q 'Token settings'"
git -C "$WORK/repo" config harness.replyStyle terse
git -C "$WORK/repo" config harness.skillLoading minimal
git -C "$WORK/repo" config harness.subagentModel economical
check "token toggles: terse replies are requested" "session '$WORK/repo' | grep -q 'Token settings:.*Keep replies terse'"
check "token toggles: minimal skill loading is requested" "session '$WORK/repo' | grep -q 'Load a skill only when'"
check "token toggles: economical subagents are requested" "session '$WORK/repo' | grep -q 'most economical model'"
git -C "$WORK/repo" config --unset harness.replyStyle
git -C "$WORK/repo" config --unset harness.skillLoading
git -C "$WORK/repo" config --unset harness.subagentModel
check "ci-watch: the default adds no setting line" "! session '$WORK/repo' | grep -q 'Workflow settings'"
git -C "$WORK/repo" config tack.ciWatch false
check "ci-watch: turning it off tells the assistant not to wait for CI" "session '$WORK/repo' | grep -q 'Workflow settings:.*Do not wait for CI'"
git -C "$WORK/repo" config --unset tack.ciWatch
for ci_mode in standard strict unleash; do
  git -C "$WORK/repo" config tack.mode "$ci_mode"
  check "ci-watch: $ci_mode mode waits for CI after a push" "session '$WORK/repo' | grep -q 'CI: after a push'"
done
for ci_mode in lite lean; do
  git -C "$WORK/repo" config tack.mode "$ci_mode"
  check "ci-watch: $ci_mode mode does not wait for CI" "! session '$WORK/repo' | grep -q 'CI: after a push'"
done
git -C "$WORK/repo" config --unset tack.mode
git -C "$WORK/repo" config harness.mode lean
check "lean mode: the rules say not to load dev-workflow" "session '$WORK/repo' | grep -q 'do not load the \`dev-workflow\` skill'"
check "lean mode: the message points to the mode's own rules" "session '$WORK/repo' | grep -q 'Apply the lean mode rules below'"
git -C "$WORK/repo" config harness.mode unleash
check "unleash mode: warns loudly at session start" "session '$WORK/repo' | grep -q 'WARNING: unleash mode is active'"
git -C "$WORK/repo" config harness.mode turbo
check "invalid mode: falls back to auto" "session '$WORK/repo' | grep -q 'mode: auto'"
git -C "$WORK/repo" config --unset harness.mode

echo "Claude hook: budget"
BUDGET="$REPO/hooks/claude/budget.sh"
export XDG_STATE_HOME="$WORK/state"
budget() { printf '{"session_id":"%s","cwd":"%s","tool_name":"Read"}' "$1" "$2" | bash "$BUDGET"; }
B="$WORK/budget-repo"
git init -q "$B"
git -C "$B" config harness.enabled true
git -C "$B" config harness.mode unleash
git -C "$B" config harness.unleashMaxToolCalls 2
check "budget: calls under the limit pass" "[ -z \"\$(budget s1 '$B')\" ] && [ -z \"\$(budget s1 '$B')\" ]"
check "budget: the call past the limit is denied" "budget s1 '$B' | grep -q '\"permissionDecision\":\"deny\"'"
check "budget: the reason names the limit" "budget s1 '$B' | grep -q 'limit of 2 tool calls'"
check "budget: each session has its own count" "[ -z \"\$(budget s2 '$B')\" ]"
check "budget: the count lives in the state directory" "[ -f '$WORK/state/agent-tack/budget/s1' ]"
check "budget: unsafe session ids are ignored" "[ -z \"\$(budget '../escape' '$B')\" ] && [ ! -e '$WORK/state/agent-tack/escape' ]"
git -C "$B" config harness.mode lite
check "budget: other modes are never limited" "[ -z \"\$(budget s1 '$B')\" ]"
git -C "$B" config harness.mode unleash
git -C "$B" config --unset harness.unleashMaxToolCalls
check "budget: no limit configured means no limit" "[ -z \"\$(budget s1 '$B')\" ]"
check "budget: malformed input is ignored" "[ -z \"\$(printf 'not json' | bash '$BUDGET')\" ]"
check "budget: registered for every tool" "grep -q 'budget.sh' '$REPO/claude/settings.json'"

echo "State retention (state-retention-days)"
BUDGET_DIR="$WORK/state/agent-tack/budget"
mkdir -p "$BUDGET_DIR"
touch -t 202001010000 "$BUDGET_DIR/old-session"
: > "$BUDGET_DIR/recent-session"
session "$B" >/dev/null
check "retention: session state older than 30 days is pruned at session start" "[ ! -e '$BUDGET_DIR/old-session' ]"
check "retention: recent session state is kept" "[ -e '$BUDGET_DIR/recent-session' ]"
touch -t "$(date -d '-3 days' +%Y%m%d%H%M 2>/dev/null || date -v-3d +%Y%m%d%H%M)" "$BUDGET_DIR/recent-session"
git -C "$B" config tack.stateRetentionDays 2
session "$B" >/dev/null
check "retention: the period follows tack config state-retention-days" "[ ! -e '$BUDGET_DIR/recent-session' ]"
git -C "$B" config --unset tack.stateRetentionDays
session "$WORK" >/dev/null
check "retention: pruning never fails the session outside a repository" "session '$WORK' | grep -q 'NOT enabled'"

echo "Claude hook: fast-check"
FAST="$REPO/hooks/claude/fast-check.sh"
F="$WORK/fast-repo"
git init -q "$F"
git -C "$F" config harness.enabled true
git -C "$F" config harness.trusted true
edited() { printf '{"cwd":"%s","tool_name":"Edit","tool_input":{"file_path":"%s/a.py"}}' "$F" "$F" | bash "$FAST"; }
check "fast-check: silent when no check is configured" "[ -z \"\$(edited)\" ]"
git -C "$F" config harness.checkFast "true"
check "fast-check: silent when the check passes" "[ -z \"\$(edited)\" ]"
git -C "$F" config harness.checkFast "echo 'tests/test_a.py::test_x FAILED'; exit 1"
check "fast-check: a failing check is reported to the assistant" "edited | grep -q '\"decision\":\"block\"'"
check "fast-check: the report includes the check output" "edited | grep -q 'test_x FAILED'"
git -C "$F" config harness.trusted false
check "fast-check: untrusted projects never run the check" "[ -z \"\$(edited)\" ]"
git -C "$F" config harness.trusted true
git -C "$F" config harness.enabled false
check "fast-check: disabled projects never run the check" "[ -z \"\$(edited)\" ]"
git -C "$F" config harness.enabled true
check "fast-check: malformed input is ignored" "[ -z \"\$(printf 'not json' | bash '$FAST')\" ]"
check "fast-check: registered after edits" "grep -q 'fast-check.sh' '$REPO/claude/settings.json'"

echo "Claude hook: stop-check"
STOP="$REPO/hooks/claude/stop-check.sh"
P2="$WORK/stop-repo"
git init -q -b main "$P2"
git -C "$P2" config harness.enabled true
mkdir -p "$P2/bin" "$P2/docs/handoffs"
printf 'bin/* | docs/usage.md\n' > "$P2/docs-map.txt"
printf 'usage\n' > "$P2/docs/usage.md"
git -C "$P2" add -A && git -C "$P2" commit -q -m "chore: initial commit"
git -C "$P2" switch -q -c feat/x
stopping() { printf '{"cwd":"%s","stop_hook_active":%s}' "$P2" "${1:-false}" | bash "$STOP"; }
check "stop-check: silent when everything is in order" "[ -z \"\$(stopping)\" ]"
printf 'x\n' > "$P2/notes.txt"
check "stop-check: uncommitted work is reported" "stopping | grep -q 'uncommitted'"
check "stop-check: the report asks the assistant to continue" "stopping | grep -q '\"decision\":\"block\"'"
check "stop-check: a second stop is never blocked" "[ -z \"\$(stopping true)\" ]"
rm "$P2/notes.txt"
printf 'tool\n' > "$P2/bin/tool"
git -C "$P2" add bin/tool && git -C "$P2" commit -q -m "feat: add tool"
check "stop-check: code changed without its mapped docs is reported" "stopping | grep -q 'bin/tool changed but docs/usage.md did not'"
printf 'usage of tool\n' > "$P2/docs/usage.md"
git -C "$P2" add docs/usage.md && git -C "$P2" commit -q -m "docs: describe tool"
check "stop-check: mapped docs updated on the branch satisfy the map" "[ -z \"\$(stopping)\" ]"
git -C "$P2" mv bin/tool bin/renamed
printf 'bin/renamed | docs/other.md\n' > "$P2/docs-map.txt"
check "stop-check: an uncommitted rename counts under its new name" "stopping | grep -q 'bin/renamed changed but docs/other.md did not'"
git -C "$P2" mv bin/renamed bin/tool
printf 'bin/* | *\n' > "$P2/docs-map.txt"
git -C "$P2" add docs-map.txt && git -C "$P2" commit -q -m "chore: wildcard docs entry"
check "stop-check: docs entries are not expanded as globs" "stopping | grep -q 'changed but \\* did not'"
printf 'bin/* | docs/usage.md\n' > "$P2/docs-map.txt"
git -C "$P2" add docs-map.txt && git -C "$P2" commit -q -m "chore: restore docs map"
printf 'more usage\n' >> "$P2/docs/usage.md"
git -C "$P2" add docs/usage.md && git -C "$P2" commit -q -m "docs: refresh usage"
printf '# Handoff\nStatus: in progress\n' > "$P2/docs/handoffs/2026-10-04-x.md"
git -C "$P2" add docs/handoffs && git -C "$P2" commit -q -m "docs(handoffs): start"
touch -t 202001010000 "$P2/docs/handoffs/2026-10-04-x.md"
GIT_COMMITTER_DATE="2030-01-01T00:00:00" git -C "$P2" commit -q --allow-empty -m "feat: later work"
check "stop-check: a stale handoff is reported" "stopping | grep -q 'handoff may be stale'"
git -C "$P2" config harness.stopCheck false
check "stop-check: can be turned off" "[ -z \"\$(stopping)\" ]"
git -C "$P2" config --unset harness.stopCheck
git -C "$P2" config harness.enabled false
check "stop-check: disabled projects are left alone" "[ -z \"\$(stopping)\" ]"
check "stop-check: malformed input is ignored" "[ -z \"\$(printf 'not json' | bash '$STOP')\" ]"
check "stop-check: registered for Stop" "grep -q 'stop-check.sh' '$REPO/claude/settings.json'"

echo "Activity log (tack config activity-log, tack log)"
LOG="$WORK/state/agent-tack/activity.log"
A="$WORK/activity-repo"
git init -q -b main "$A"
git -C "$A" config tack.enabled true
deny_in() { printf '{"cwd":"%s","tool_input":{"command":"git commit --no-verify"}}' "$A" | bash "$GUARD" "$@" >/dev/null; }
log_cmd() { (cd "$A" && "$CLI" log "$@"); }
deny_in
check "activity log: off by default" "[ ! -e '$LOG' ]"
check "activity log: tack log explains how to turn it on" "log_cmd | grep -q 'tack config activity-log true'"
git -C "$A" config tack.activityLog true
deny_in
check "activity log: guard decisions are recorded" "grep -q 'claude.*guard deny.*no-verify' '$LOG'"
deny_in --codex
check "activity log: only the user can read it (it may hold commands)" "[ \"\$(ls -l '$LOG' | cut -c1-10)\" = '-rw-------' ]"
check "activity log: Codex runs are labelled" "grep -q 'codex.*guard deny' '$LOG'"
printf '{"cwd":"%s"}' "$A" | bash "$SESSION" >/dev/null
check "activity log: session starts are recorded with the mode" "grep -q 'session-start.*mode=auto' '$LOG'"
printf 'x\n' > "$A/dirty.txt"
printf '{"cwd":"%s","stop_hook_active":false}' "$A" | bash "$STOP" >/dev/null
check "activity log: Stop findings are recorded" "grep -q 'stop-check.*uncommitted' '$LOG'"
check "activity log: each line starts with a UTC timestamp" "grep -qE '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]{8}Z' '$LOG'"
check "activity log: tack log prints the recent entries" "log_cmd | grep -q 'guard deny'"
check "activity log: tack log N limits the entries" "[ \"\$(log_cmd 1 | wc -l | tr -d ' ')\" = 1 ] && log_cmd 1 | grep -q stop-check"
check "activity log: tack log rejects a bad count" "log_cmd nope >/dev/null 2>&1; [ \$? -eq 2 ]"
git -C "$A" config tack.activityLog false
deny_in
check "activity log: turning it off stops recording" "[ \"\$(grep -c 'guard deny' '$LOG')\" = 2 ]"

echo "Claude hook: format-file"
FORMAT="$REPO/hooks/claude/format-file.sh"
P="$WORK/project"
mkdir -p "$P/node_modules/.bin" "$P/src"
git init -q "$P"
git -C "$P" config --local harness.trusted true
cat > "$P/node_modules/.bin/prettier" <<'EOF'
#!/usr/bin/env bash
for a in "$@"; do case "$a" in -*) ;; *) echo "// formatted" >> "$a" ;; esac; done
EOF
chmod +x "$P/node_modules/.bin/prettier"
echo "const a=1" > "$P/src/a.ts"
format() { printf '{"tool_name":"Edit","tool_input":{"file_path":"%s"}}' "$1" | bash "$FORMAT"; }
format "$P/src/a.ts"
check "no formatter config → file untouched" "! grep -q formatted '$P/src/a.ts'"
echo '{}' > "$P/.prettierrc"
format "$P/src/a.ts"
check "prettier configured → file formatted" "grep -q formatted '$P/src/a.ts'"
echo "const b=2" > "$P/src/b.ts"
git -C "$P" config harness.enabled false
format "$P/src/b.ts"
check "project not enabled → its formatter binaries are never run" "! grep -q formatted '$P/src/b.ts'"
git -C "$P" config --unset harness.enabled
mkdir -p "$WORK/no-git"
echo "const c=3" > "$WORK/no-git/c.ts"
format "$WORK/no-git/c.ts"
check "file outside any git repo → untouched" "! grep -q formatted '$WORK/no-git/c.ts'"

STUBS="$WORK/stubs"
mkdir -p "$STUBS"
for tool in rustfmt cargo; do
  printf '#!/usr/bin/env bash\necho "%s $*" >> "%s/format-calls"\n' "$tool" "$WORK" > "$STUBS/$tool"
  chmod +x "$STUBS/$tool"
done
RS="$WORK/rust-project"
mkdir -p "$RS/src"
git init -q "$RS"
git -C "$RS" config --local harness.trusted true
printf '[package]\nname = "demo"\nedition = "2021"\n' > "$RS/Cargo.toml"
echo "fn main(){}" > "$RS/src/main.rs"
printf '{"tool_input":{"file_path":"%s"}}' "$RS/src/main.rs" | PATH="$STUBS:$PATH" bash "$FORMAT"
check "rust: rustfmt formats only the edited file" "grep -q \"^rustfmt --edition 2021 $RS/src/main.rs\$\" '$WORK/format-calls'"
check "rust: cargo fmt (whole crate) is not used" "! grep -q '^cargo' '$WORK/format-calls'"
echo "x = 1" > "$P/src/a.py"
format "$P/src/a.py"
check "python file without ruff/black config untouched" "[ \"\$(cat '$P/src/a.py')\" = 'x = 1' ]"
check "missing file is ignored" "format '$P/nope.ts'"
check "always exits 0" "printf 'garbage' | bash '$FORMAT'"

echo
echo "$PASSED passed, $FAILED failed"
[ "$FAILED" -eq 0 ]
