#!/usr/bin/env python3
"""Render a harness agent (agents/<name>.md) as a Codex custom agent (TOML).

Usage: codex_agents.py <agent.md>   prints the TOML on stdout
"""
import sys
from pathlib import Path

READ_ONLY_TOOLS = {"Read", "Grep", "Glob", "Bash", "WebFetch", "WebSearch"}


def parse(path):
    text = Path(path).read_text()
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter")
    header, _, body = text[4:].partition("\n---\n")
    fields = {}
    for line in header.splitlines():
        key, sep, value = line.partition(":")
        if sep:
            fields[key.strip()] = value.strip()
    if not fields.get("name") or not fields.get("description"):
        raise ValueError(f"{path}: name and description are required")
    return fields, body.strip() + "\n"


def basic(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def multiline(value):
    # A TOML basic multi-line string; escaping backslashes and quotes keeps any body valid.
    return '"""\n' + value.replace("\\", "\\\\").replace('"', '\\"') + '"""'


def render(path):
    fields, body = parse(path)
    lines = [
        "# Generated by tack from agents/" + Path(path).name + "; edits are preserved, not overwritten.",
        "name = " + basic(fields["name"]),
        "description = " + basic(fields["description"]),
    ]
    tools = {tool.strip() for tool in fields.get("tools", "").split(",") if tool.strip()}
    # Agents that cannot edit files get a read-only sandbox; editing agents inherit Codex's.
    if tools and tools <= READ_ONLY_TOOLS:
        lines.append('sandbox_mode = "read-only"')
    lines.append("developer_instructions = " + multiline(body))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: codex_agents.py <agent.md>")
    sys.stdout.write(render(sys.argv[1]))
